- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'USER') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml
    - include: tasks/git-setup.yml
    - include: tasks/node-setup.yml
