- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update repositories
      become: true
      apt: 
        update_cache: true
        force_apt_get: true
        state: present
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml
    - include: tasks/git-setup.yml
    - include: tasks/node-setup.yml
