- name: Install stow
  apt:
    name: stow
    state: present
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:LHernZ/.dotfiles'
    dest: "/home/{{ lookup('env', 'USER') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: wip
  become_user: "{{ lookup('env', 'USER') }}"

- name: Make executable
  shell: chmod +x ./ubuntu

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu

- name: Install TMUX
  apt:
    name: tmux
    state: present
- name: Install TPM
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '$HOME/.tmux/plugins/tpm'

