- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  args:
    creates: "{{ ansible_env.USER }}/.nvm/nvm.sh"
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
- name: Install latest node
  shell: export NVM_DIR=\"$HOME/.nvm\"\n[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\" && nvm install node
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"