- name: Ensure .ssh directory exists.
  become_user: root
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: Install ssh key
  become_user: "{{ lookup('env', 'USER') }}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', '.ssh/id_ed25519.pub') }}"
- name: Copy SSH Keys
  ansible.builtin.copy:
    src: .ssh/id_ed25519
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    mode: '0600'
    decrypt: 'yes'
- name: Ensure .ssh directory exists.
  become_user: "{{ lookup('env', 'USER') }}"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: Install ssh key
  become_user: "{{ lookup('env', 'USER') }}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', '.ssh/id_ed25519.pub') }}"
- name: Copy SSH Keys
  ansible.builtin.copy:
    src: .ssh/id_ed25519
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    mode: '0600'
    decrypt: 'yes'
